export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE';
export type SELECT_EMPLOYEE = typeof SELECT_EMPLOYEE;

export const SELECT_DEPARTMENT = 'SELECT_DEPARTMENT';
export type SELECT_DEPARTMENT = typeof SELECT_DEPARTMENT;

export const SELECT_LOCATION = 'SELECT_LOCATION';
export type SELECT_LOCATION = typeof SELECT_LOCATION;


export const EMPTY_GUID = '0000';